### ISSUE TITLE
No connection adapters were found

### ISSUE THREAD

**Issue by outscale-hai** [narkhedesam/Proxy-List-Scrapper#5] opened 2021-01-16 21:22 UTC
I tried to retrieve all proxies, but this error is raised
```
requests.exceptions.InvalidSchema: No connection adapters were found for "('https://www.sslproxies.org/',)"
```
Here is my code
```
if __name__ == "__main__":
    # links = read_links('Links.txt')
    scrapper = Scrapper(category='ALL', print_err_trace=False)
    data = scrapper.getProxies()
    for item in data.proxies:
        print('{0}:{1}'.format(item.ip, item.port))
    print('Length : {0}'.format(data.len))
```
Do you have any idea how to fix this error ?

I tried to update `requests` module, but it doesn't work
```
pip3 install requests==2.23.0
```

**Comment by Shivanshu10** [comment] 2021-01-18 05:40
I am facing the same issue

**Comment by narkhedesam** [comment] 2021-01-19 06:07
we fixed this issue in the latest version

Please upgrade to the latest version of Proxy-List-Scrapper
`pip install --upgrade Proxy-List-Scrapper`

**Comment by narkhedesam** [comment] 2021-01-20 12:28
Please let me know if the issue is fixed...will close this issue.

**Comment by outscale-hai** [comment] 2021-01-20 17:41
Error fixed, thank you

**Closed** 2021-01-20 17:40 UTC
